DELETE FROM STRATEGY WHERE STRATEGY = "st01";
DELETE FROM STRATEGY WHERE STRATEGY = "st02";
DELETE FROM STRATEGY WHERE STRATEGY = "st03";
DELETE FROM STRATEGY WHERE STRATEGY = "st04";

INSERT INTO STRATEGY(strategy) VALUES ("st01");
INSERT INTO STRATEGY(strategy) VALUES ("st02");
INSERT INTO STRATEGY(strategy) VALUES ("st03");
INSERT INTO STRATEGY(strategy) VALUES ("st04");

DELETE FROM MODEL WHERE STRATEGY = "st01";
DELETE FROM MODEL WHERE STRATEGY = "st02";
