wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.23
    framework: huggingface
    huggingface_version: 3.3.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      2:
      - 1
      - 3
      - 5
      - 11
      3:
      - 1
      4: 3.8.5
      5: 0.10.23
      6: 3.3.1
      8:
      - 5
auto_sub:
  desc: null
  value: false
batch_size:
  desc: null
  value: 16
data_dir:
  desc: null
  value: /home/j-gunmo/storage/data/input/data/
data_kind:
  desc: null
  value: dataset_v1
dataset_idx:
  desc: null
  value: 0
debug:
  desc: null
  value: false
delta:
  desc: null
  value: 0
device:
  desc: null
  value: cuda:0
epochs:
  desc: null
  value: 20
max_seq_length:
  desc: null
  value: 128
model_name_or_path:
  desc: null
  value: monologg/koelectra-base-discriminator
ms_name:
  desc: null
  value: koelectra
num_labels:
  desc: null
  value: 42
optimizer:
  desc: null
  value: adamw
optimizer_hp:
  desc: null
  value:
    lr: 5.0e-05
patience:
  desc: null
  value: 5
sampler:
  desc: null
  value: random
scheduler:
  desc: null
  value: sgdr
scheduler_hp:
  desc: null
  value:
    cycle_mult: 1.0
    first_cycle_steps: 200
    gamma: 0.5
    warmup_steps: 50
strategy:
  desc: null
  value: st01
submit_dir:
  desc: null
  value: /home/j-gunmo/desktop/00.my-project/17.P-Stage-T1003/2-STAGE/submits
warmup_steps:
  desc: null
  value: 500
weight_decay:
  desc: null
  value: 0.01
weight_dir:
  desc: null
  value: /home/j-gunmo/desktop/00.my-project/17.P-Stage-T1003/2-STAGE/weights
